---
title: "Problem Set 7"
author: "Rebecca Xi"
date: "4/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(skimr)
library(tidyverse)

# Read in the data

data <- read.csv('raw-data/HSall_members.csv')
```


## Question 1: Conduct exploratory data analysis

### 1A) Summary Statistics

```{r 1A, echo=FALSE}

# I create a tibble from the csv data, filtering for Senators (chamber ==
# “Senate”) and Representatives (chamber == “House”) in the 116th Congress and
# filtering out all independents (party_code == 328). I then create three new
# variables: "party", which records either “Democrat” (party_code == 100) or
# “Republican” (part_code == 200) using an efficient ifelse condition; "age",
# which is 2019 (when the 116th Congress was sworn in) minus birth year; and
# "nominate_percentile", which gives the percentile rank of nominate_dim1 using
# the percent_rank() function.

sen_rep_116 <- data %>% 
  filter(
    congress == 116, 
    chamber == "Senate" | chamber == "House",
    party_code != 328
  ) %>% 
  mutate(
    party = ifelse(party_code == 100, "Democrat", "Republican"),
    age = 2019 - born,
    nominate_percentile = percent_rank(nominate_dim1)
  )

# Here I print the output of calling skim on the nominate_percentile and age
# variables, as an alternative to summary

 skim(sen_rep_116$nominate_percentile)
 skim(sen_rep_116$age)
```


### 1B) Visualizing a single variable

```{r 1B, echo=FALSE}

# Here I create a histogram showing the distribution of congressional ages,
# colored in by party (Democrat or Republican). I use the fill argument to
# indicate party, since I am personally interested in seeing the distribution of
# ages across parties (do Democrats or Republicans generally skew older?). I use
# facet_wrap to wrap the data by House and by Senate so I get an age
# distribution for each one, which is helpful in thinking about (1) the contrast
# in age distributions, if any, between House and Senate,  and (2) the
# distribution of Democrats and Republicans across House and Senate.

age_plot <- sen_rep_116 %>% 
  select(age, party, chamber) %>% 
  ggplot(aes(x = age, fill = party)) +
    geom_histogram(bins = 40) +
    facet_wrap(vars(chamber)) +
    labs(
      title = "Distribution of Congressional Ages",
      subtitle = "for Democrats and Republicans at the 116th Congress",
      source = "Voteview: Congressional Roll-Call Votes Database",
      x = "Age",
      y = "Count"
    ) +
    scale_fill_manual(values = c("Democrat" = "blue", "Republican" = "red")) +
    theme_classic()
age_plot
  
# I copy-paste the above code here and modify for nominate_percentile. The goal
# here is to be able to visualize the split between "liberals" and
# "conservatives", which unsurprisingly corresponds to the split between
# Democrats and Republicans. By eyeballing, I observe a slighter more liberal
# House and a slightly more conservative Senate.

nom_perc_plot <- sen_rep_116 %>% 
  select(nominate_percentile, party, chamber) %>% 
  ggplot(aes(x = nominate_percentile, fill = party)) +
    geom_histogram(bins = 40) +
    facet_wrap(vars(chamber)) +
    labs(
      title = "Distribution of Primary Dimension Outcomes",
      subtitle = "for Democrats and Republicans at the 116th Congress",
      source = "Voteview: Congressional Roll-Call Votes Database",
      x = "Percentile Rank of Primary Dimension",
      y = "Count"
    ) +
    scale_fill_manual(values = c("Democrat" = "blue", "Republican" = "red")) +
    theme_classic()
nom_perc_plot
```


### 1C) Bivariate Correlations

### 1D) Plotting Bivariate relationships




## Question 2: Run a single regression


### 2A) Using lm()

### 2B) Interpreting results

### 2C) Regression and the Rubin Causal Model





## Question 3: Generalize to many regressions



